variables:
  SHOPPING_SERVICE_ENVIRONMENT: production
  SHOPPING_SERVICE_DB_CONNECTION_STRING: $env:SHOPPING_SERVICE_DB_CONNECTION_STRING

jobs:
- job: DevelopmentJob
  displayName: Build, Test, and Create Artifact Job
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - bash: dotnet restore
    - bash: dotnet test
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'shopping-service'
        targetPath: 'ShoppingService.Api/bin/Release/netcoreapp2.2'
- deployment: DeployJob
  dependsOn: DevelopmentJob
  displayName: Deploy to Staging Job
  pool:
    vmImage: 'ubuntu-16.04'
  environment: staging
  strategy:
    runOnce:
      deploy:
        steps:
          - task: DownloadPipelineArtifact@0
            inputs:
              artifactName: 'artifactName'
              targetPath: $(System.DefaultWorkingDirectory)

